name: CI

on:
  push:
    branches: [ main, stage, develop ]
  pull_request:
    branches: [ main, stage, develop ]

jobs:
  rust-ci:
    uses: wiliest0r/gh-actions-central/.github/workflows/rust-wasm-ci.yml@main
    with:
      rust-version: 'stable'
      target: 'wasm32-wasip1'
      max-size-mb: 3
